version: '3.8'

services:
  laravel:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      APP_DEBUG: '${APP_DEBUG:-false}'
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel_db}
      DB_USERNAME: ${DB_USERNAME:-admin}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
      target: builder
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      API_URL: http://laravel
    volumes:
      - ./nextjs:/app:cached
      - next_node_modules:/app/node_modules
      - next_cache:/app/.next
    command: npm run dev
    depends_on:
      - laravel
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel_db}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:cached
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME:-admin}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
  next_node_modules:
  next_cache: